title:        open-source-documentation-jekyll-theme
name:         Open Source Documentation (Jekyll Theme)
description:  A Jekyll theme for open source project documentation sites.
url:          https://github.com/andrewgjohnson/open-source-documentation-jekyll-theme
favicon:      https://github.githubassets.com/favicon.ico
cover_image:  mountains
